### ISSUE TITLE
Infografía 2

### ISSUE THREAD

**Issue by kirus21** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-kirus21#1]
[Infografia-Rigoberto.Suridai.Pascual.Reyes.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-kirus21/files/8566445/Infografia-Rigoberto.Suridai.Pascual.Reyes.pdf)

**Comment by Abraham890** [comment]
calificación: 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
